# Selenium Test Configuration
browser: chrome                    
headless: true                    
download_directory: ./downloads  
file_type: application/octet-stream 
timeout: 30                     
retry_attempts: 3                 
window_size: "1920,1080"      
use_user_data_dir: false          # Disabled by default to avoid conflicts (especially in CI)

# Test Configuration
test_timeout: 60           
implicit_wait: 10                 
explicit_wait: 10                 
page_load_timeout: 60       

# Logging Configuration
log_level: INFO                   # Options: DEBUG, INFO, WARNING, ERROR
log_file: logs/test.log         

base_url: 'https://www.google.com/'

excel_data_file: data/excel_data.xlsx
excel_data_sheet: Sheet3

enable_screenshots: true
# enable_logs: true
# enable_video: true
# enable_network: true
# enable_database: true
# enable_console: true