# Selenium Test Configuration
browser: chrome                    # Options: chrome, firefox
headless: false                    # Run browser in headless mode
download_directory: ./downloads   # Directory for downloaded files
file_type: application/octet-stream # MIME type for downloads
timeout: 30                       # Default timeout in seconds
retry_attempts: 3                 # Number of retry attempts for browser startup
window_size: "1920,1080"         # Browser window size (width,height)
use_user_data_dir: true

# Test Configuration
test_timeout: 60                  # Test timeout in seconds
implicit_wait: 10                 # Implicit wait time in seconds
explicit_wait: 10                 # Implicit wait time in seconds
page_load_timeout: 60            # Increased page load timeout in seconds

# Logging Configuration
log_level: INFO                   # Options: DEBUG, INFO, WARNING, ERROR
log_file: logs/test.log          # Log file path

base_url: https://www.moneycontrol.com/fixed-income/calculator/state-bank-of-india/fixed-deposit-calculator-SBI-BSB001.html

excel_data_file: data/excel_data.xlsx
excel_data_sheet: Sheet3

enable_screenshots: true
# enable_logs: true
# enable_video: true
# enable_network: true
# enable_database: true
# enable_console: true