# Selenium Test Configuration
browser: chrome
headless: true
download_directory: ./downloads
file_type: application/octet-stream
timeout: 30
retry_attempts: 3
window_size: "1920,1080"

# Test Configuration - Increased timeouts for CI environment
test_timeout: 120
implicit_wait: 15
page_load_timeout: 60
script_timeout: 30

# Network and Performance Configuration
enable_images: false
enable_javascript: false
connection_timeout: 60
read_timeout: 120

# Logging Configuration
log_level: INFO
log_file: logs/test.log

base_url: https://www.moneycontrol.com/fixed-income/calculator/state-bank-of-india/fixed-deposit-calculator-SBI-BSB001.html

excel_data_file: data/excel_data.xlsx
excel_data_sheet: Sheet3

enable_screenshots: true
# enable_logs: true
# enable_video: true
# enable_network: true
# enable_database: true
# enable_console: true

# CI/CD Specific Settings
ci_mode: true
max_wait_time: 30
retry_on_failure: true
cleanup_on_exit: true
